# Generated by Django 4.0.3 on 2022-04-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grip', models.TextField(max_length=10, verbose_name='Хват')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=15, verbose_name='Амплуа')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Имя')),
                ('surname', models.TextField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('grip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.grip', verbose_name='Хват')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.roles', verbose_name='Амплуа')),
            ],
        ),
    ]
