# Generated by Django 4.0.3 on 2022-04-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Игроки'},
        ),
    ]
