# Generated by Django 4.0.3 on 2022-04-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_roles_role_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grip',
            options={'verbose_name_plural': 'Хват'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Амплуа'},
        ),
    ]
