# Generated by Django 4.0.3 on 2022-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_player_number_alter_grip_grip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img_player',
            field=models.ImageField(default='images/default_img.png', upload_to='images/'),
        ),
    ]
