# Generated by Django 4.0.3 on 2022-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_player_img_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='img_player',
            field=models.ImageField(default='images/default_img.png', upload_to='images/', verbose_name='Фото'),
        ),
    ]
