# Generated by Django 4.0.3 on 2022-05-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_player_img_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grip',
            options={'verbose_name': 'Хват', 'verbose_name_plural': 'Хват'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Амплуа', 'verbose_name_plural': 'Амплуа'},
        ),
    ]
